# Generated by Django 5.0.6 on 2025-08-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('kept', 'Kept'), ('disposed', 'Disposed')], default='kept', max_length=10)),
                ('media_type', models.CharField(choices=[('physical', 'Physical'), ('download', 'Download'), ('rip', 'Rip')], default='physical', max_length=10)),
                ('tmdb_id', models.IntegerField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, max_length=500)),
                ('overview', models.TextField(blank=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('genres', models.CharField(blank=True, max_length=255)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
