# Generated by Django 5.0.6 on 2025-08-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd',
            name='imdb_id',
            field=models.CharField(blank=True, help_text='IMDB ID (e.g., tt1234567)', max_length=20),
        ),
    ]
