# Generated by Django 5.0.6 on 2025-08-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_dvd_imdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd',
            name='box_set_name',
            field=models.CharField(blank=True, help_text='Name of the box set (if applicable)', max_length=255),
        ),
        migrations.AddField(
            model_name='dvd',
            name='is_box_set',
            field=models.BooleanField(default=False, help_text='Is this part of a box set?'),
        ),
        migrations.AddField(
            model_name='dvd',
            name='is_tartan_dvd',
            field=models.BooleanField(default=False, help_text='Is this a Tartan DVD release?'),
        ),
        migrations.AddField(
            model_name='dvd',
            name='is_unopened',
            field=models.BooleanField(default=False, help_text='Is this DVD still unopened?'),
        ),
    ]
