# Generated by Django 5.0.6 on 2025-08-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_dvd_box_set_name_dvd_is_box_set_dvd_is_tartan_dvd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd',
            name='storage_box',
            field=models.CharField(blank=True, help_text='Storage box location (for kept items)', max_length=100),
        ),
    ]
