# Generated by Django 5.0.6 on 2025-08-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_dvd_storage_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd',
            name='is_unwatched',
            field=models.BooleanField(default=False, help_text='Have you not watched this movie yet?'),
        ),
    ]
