# Generated by Django 5.0.6 on 2025-08-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_dvd_is_unwatched'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated current market value', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dvd',
            name='price_source',
            field=models.CharField(blank=True, help_text='Source of price estimate (e.g., eBay, Amazon, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='dvd',
            name='price_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the price estimate was last updated', null=True),
        ),
        migrations.AddField(
            model_name='dvd',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price you paid for this DVD', max_digits=10, null=True),
        ),
    ]
