# Generated by Django 5.0.6 on 2025-08-11 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_dvd_estimated_price_dvd_price_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dvd',
            name='estimated_price',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='price_source',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='price_updated_at',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='purchase_price',
        ),
    ]
