# Generated by Django 5.0.6 on 2025-08-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_remove_pricing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd',
            name='uk_certification',
            field=models.CharField(blank=True, help_text='UK film certification (e.g., U, PG, 12, 15, 18)', max_length=10),
        ),
    ]
