# Generated by Django 5.0.6 on 2025-08-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_dvd_uk_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd',
            name='budget',
            field=models.BigIntegerField(blank=True, help_text='Movie budget in USD', null=True),
        ),
        migrations.AddField(
            model_name='dvd',
            name='original_language',
            field=models.CharField(blank=True, help_text='Original language of the movie', max_length=10),
        ),
        migrations.AddField(
            model_name='dvd',
            name='production_companies',
            field=models.TextField(blank=True, help_text='Production companies, comma-separated'),
        ),
        migrations.AddField(
            model_name='dvd',
            name='revenue',
            field=models.BigIntegerField(blank=True, help_text='Movie revenue in USD', null=True),
        ),
        migrations.AddField(
            model_name='dvd',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dvd',
            name='tmdb_user_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='TMDB user score out of 10', max_digits=4, null=True),
        ),
    ]
