# Generated by Django 5.0.6 on 2025-08-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_dvd_budget_dvd_original_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dvd',
            name='poster_url',
        ),
        migrations.AddField(
            model_name='dvd',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
