# Generated by Django 5.0.6 on 2025-08-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_add_app_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd',
            name='is_downloaded',
            field=models.BooleanField(default=False, help_text='Has this DVD been downloaded?'),
        ),
    ]
