# Generated by Django 5.0.6 on 2025-08-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_dvd_is_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd',
            name='copy_number',
            field=models.PositiveSmallIntegerField(default=1, help_text='Copy number (1, 2, 3, etc.) for duplicate movies'),
        ),
        migrations.AddField(
            model_name='dvd',
            name='duplicate_notes',
            field=models.CharField(blank=True, help_text='Notes about this copy (e.g., "Director\'s Cut", "Region 2", "Special Edition")', max_length=255),
        ),
    ]
