# Generated by Django 5.0.6 on 2025-09-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_add_duplicate_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd',
            name='location',
            field=models.CharField(blank=True, help_text='Location (for unboxed items)', max_length=255),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='status',
            field=models.CharField(choices=[('kept', 'Kept'), ('disposed', 'Disposed'), ('unboxed', 'Unboxed')], default='kept', max_length=10),
        ),
    ]
