# Generated by Django 5.0.6 on 2025-09-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_dvd_location_alter_dvd_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd',
            name='director',
            field=models.CharField(blank=True, help_text='Director of the movie', max_length=255),
        ),
    ]
