# Generated by Django 5.0.6 on 2025-09-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_dvd_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd',
            name='yts_data',
            field=models.JSONField(blank=True, help_text='Cached YTS torrent data', null=True),
        ),
        migrations.AddField(
            model_name='dvd',
            name='yts_last_updated',
            field=models.DateTimeField(blank=True, help_text='When YTS data was last refreshed', null=True),
        ),
    ]
