# Generated by Django 5.0.6 on 2025-09-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_dvd_yts_data_dvd_yts_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd',
            name='has_cached_torrents',
            field=models.BooleanField(default=False, help_text='Whether this DVD has torrents available (cached result for fast filtering)'),
        ),
    ]
