# Generated by Django 5.0.6 on 2025-09-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_add_cached_torrents_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd',
            name='disk_type',
            field=models.CharField(choices=[('DVD', 'DVD'), ('BluRay', 'BluRay')], default='DVD', max_length=10),
        ),
    ]
